
CC=gcc
CFLAGS=-I tests/mocks -DRESOURCE_ID_WEATHER_CLEAR_DAY=1 -DRESOURCE_ID_WEATHER_CLEAR_NIGHT=2 -DRESOURCE_ID_WEATHER_CLOUDY=3 -DRESOURCE_ID_WEATHER_HEAVY_RAIN=4 -DRESOURCE_ID_WEATHER_HEAVY_SNOW=5 -DRESOURCE_ID_WEATHER_LIGHT_RAIN=6 -DRESOURCE_ID_WEATHER_LIGHT_SNOW=7 -DRESOURCE_ID_WEATHER_PARTLY_CLOUDY_NIGHT=8 -DRESOURCE_ID_WEATHER_PARTLY_CLOUDY=9 -DRESOURCE_ID_WEATHER_RAINING_AND_SNOWING=10 -DRESOURCE_ID_WEATHER_THUNDERSTORM=11 -DRESOURCE_ID_WEATHER_GENERIC=12

test_weather:
	$(CC) $(CFLAGS) tests/test_weather.c src/c/weather.c tests/mocks/pebble_mock.c -o tests/run_tests
	./tests/run_tests

clean:
	rm -f tests/run_tests
